# # Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'


add_newline = true

format = """$time $all"""

[character]
success_symbol = "[╰┈➤](bold green)"
error_symbol = "[╰┈➤](red)"

[git_branch]
symbol = "🌱 "
truncation_length = 4
truncation_symbol = ""
# ignore_branches = ["master", "main"]
format = "[](fg:#ffffff bg:none)[🌱](fg:#282c34 bg:#ffffff)[](fg:#ffffff bg:#24c90a)[ $branch]($style)[](fg:#24c90a bg:none) "
style = "fg:#ffffff bg:#24c90a"

[git_commit]
commit_hash_length = 4
tag_symbol = "🔖 "
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "green"

[git_status]
format="[](fg:#ffffff bg:none)[🥶](fg:#282c34 bg:#ffffff)[ ](fg:#ffffff bg:#4da0ff)[$modified](fg:#282c34 bg:#4da0ff)[$untracked](fg:#282c34 bg:#4da0ff)[$staged](fg:#282c34 bg:#4da0ff)[$renamed](fg:#282c34 bg:#4da0ff)[](fg:#4da0ff bg:none)"
conflicted = ""
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
up_to_date = "🥰"
untracked = "🤷"
stashed = "📦"
modified = "📝"
renamed = "👅"
deleted = "🗑️"
style = "red"
disabled = false

# [git_state]
# rebase = "REBASING"
# merge =	"MERGING"
# revert = "REVERTING"
# cherry_pick = "CHERRY-PICKING"
# bisect = "BISECTING"
# am = "AM"
# am_or_rebase = "AM/REBASE"
# style =	"yellow"
# format = '\([$state( $progress_current/$progress_total)]($style)\) '
# disabled = true


[directory]
format = "[](fg:#ffffff bg:none)[⾕](fg:#282c34 bg:#ffffff)[](fg:#ffffff bg:#1c420b)[ $path]($style)[](fg:#1c420b bg:none) "
style = "fg:#ffffff bg:#1c420b"
truncation_length = 3
truncate_to_repo=false
home_symbol = ""

[nodejs]
symbol = "🤖 "
disabled = true

[package] 
symbol = "📦 "
disabled = true

[python]
symbol = "🐍 "

[rust]
symbol = "🦀 "

[time]
disabled = false
format="[](fg:#ffffff bg:none)[ⴵ](fg:#282c34 bg:#ffffff)[](fg:#ffffff bg:#2d0de0)[ $time]($style)[](fg:#2d0de0 bg:none)"
time_format = "%T" #change to %R to only have HH:MM
style="fg:#ffffff bg:#2d0de0"

 #[custom.emoji]
 #description = "Displays a (pseudo) random emoji for each prompt"
 #command = "EMOJIS=(⛵️ 🛰 🪐 🚀 🧡 🔭 🌍 💫 ☄️ ✨ 🌠 🌌 ⭐️); EMOJI_INDEX=$(( $RANDOM % 12 + 0 )); echo ${EMOJIS[$EMOJI_INDEX]}"
 #when = "1"
 #shell = ["cmd /C"]
 #format = "$output"
